/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;
import productos.*;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Jorge Tapia Flores
 */
public class ControlStock extends javax.swing.JFrame {

    /**
     * Creates new form ControlStock
     */
    public static ArrayList<Industriales> listaInd = new ArrayList<>();
    public static ArrayList<Oficina> listaOfi = new ArrayList<>();
    public static ArrayList<Utensilios> listaUten = new ArrayList<>();
    public static ArrayList<Comestibles> listaCome = new ArrayList<>();
    public ControlStock() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        letrero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Control de Stock");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 30, 220, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Cantidad a ingresar");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 100, 180, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(530, 100, 130, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("Nombre del Producto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 100, 180, 50);
        getContentPane().add(nombre);
        nombre.setBounds(50, 175, 173, 41);

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        getContentPane().add(cantidad);
        cantidad.setBounds(283, 175, 177, 41);
        getContentPane().add(precio);
        precio.setBounds(530, 170, 158, 41);

        jButton1.setText("Añadir a Utensilios");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(54, 268, 179, 62);

        jButton2.setText("Añadir a comestibles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 361, 183, 72);

        jButton3.setText("Añadir a industriales");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(283, 268, 177, 62);

        jButton4.setText("Añadir a oficina");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(283, 361, 177, 72);

        jButton5.setText("Atras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(540, 310, 144, 62);
        getContentPane().add(letrero);
        letrero.setBounds(550, 40, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        
    }//GEN-LAST:event_cantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean bandera = true;
        for (Utensilios f : listaUten){
            if(f.getNombre().equals(nombre.getText())){
                f.addStock(Integer.parseInt(cantidad.getText()));
                f.setCosto(Double.parseDouble(precio.getText()));
                letrero.setText("entramos");
                bandera = false;
            }   
        } 
        if (bandera == true){
            Utensilios ute = new Utensilios(); 
            ute.addStock(Integer.parseInt(cantidad.getText()));
            ute.setNombre(nombre.getText());
            ute.setCosto(Double.parseDouble(precio.getText()));
            listaUten.add(ute);
            letrero.setText(ute.getNombre());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean bandera = true;
        for (Comestibles f : listaCome){
            if(f.getNombre().equals(nombre.getText())){
                f.addStock(Integer.parseInt(cantidad.getText()));
                f.setCosto(Double.parseDouble(precio.getText()));
                letrero.setText(f.getNombre());
                bandera = false;
            }   
        } 
        if (bandera == true){
        Comestibles ute = new Comestibles(); 
        ute.addStock(Integer.parseInt(cantidad.getText()));
        ute.setNombre(nombre.getText());
        ute.setCosto(Double.parseDouble(precio.getText()));

        listaCome.add(ute);
        letrero.setText(ute.getNombre());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean bandera = true;
        for (Industriales f : listaInd){
            if(f.getNombre().equals(nombre.getText())){
                f.addStock(Integer.parseInt(cantidad.getText()));
                f.setCosto(Double.parseDouble(precio.getText()));
                letrero.setText(f.getNombre());
                bandera = false;
            }   
        }
        if (bandera == true){
        Industriales ute = new Industriales(); 
        ute.addStock(Integer.parseInt(cantidad.getText()));
        ute.setNombre(nombre.getText());
        ute.setCosto(Double.parseDouble(precio.getText()));
        listaInd.add(ute);
        letrero.setText(ute.getNombre());}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean bandera = true;
        for (Oficina f : listaOfi){
            if(f.getNombre().equals(nombre.getText())){
                f.addStock(Integer.parseInt(cantidad.getText()));
                f.setCosto(Double.parseDouble(precio.getText()));
                letrero.setText(f.getNombre());
                bandera = false;
            }   
        }
        if (bandera == true){
        Oficina ute = new Oficina(); 
        ute.addStock(Integer.parseInt(cantidad.getText()));
        ute.setNombre(nombre.getText());
        ute.setCosto(Double.parseDouble(precio.getText()));
        listaOfi.add(ute);
        letrero.setText(ute.getNombre());}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        EjecutaProducto jfrm2= new EjecutaProducto();
        jfrm2.setSize(EjecutaProducto.ancho, EjecutaProducto.alto);
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel letrero;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    // End of variables declaration//GEN-END:variables
}
