/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import java.util.ArrayList;
import java.util.Iterator;
import productos.*;
import java.util.List;

/**
 *
 * @author Jorge Tapia Flores
 */
public class Venta1 extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    public static ArrayList<Factura> listaFact = new ArrayList<>();
    public Venta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jTextField1.setText("jTextField1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setText("Control de Ventas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 0, 340, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nombre del producto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 120, 190, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 190, 97, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Stock restante");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 250, 160, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Subtotal ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 350, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("IVA ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 400, 170, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Total ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 440, 140, 24);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(440, 120, 220, 40);

        jTextField3.setText("jTextField3");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(440, 180, 220, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 350, 190, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 400, 192, 22);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 440, 125, 24);

        jToggleButton2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jToggleButton2.setText("Atras");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(60, 550, 200, 60);

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 550, 220, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tipo de Producto");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(160, 290, 210, 60);

        jToggleButton3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jToggleButton3.setText("TotalFinal");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(680, 550, 210, 60);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("jLabel9");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(440, 240, 230, 40);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(440, 300, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        listaFact.clear();
        // TODO add your handling code here:
        EjecutaProducto jfrm2 = new EjecutaProducto();
        jfrm2.setSize(EjecutaProducto.ancho, EjecutaProducto.alto);
        jfrm2.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String aux = jTextField2.getText();
        int aux2 = Integer.parseInt(jTextField3.getText());
        
        try{
            for (Industriales d : ControlStock.listaInd) {
                   if (d.getNombre().equals(aux)) {
                       d.removeStock(aux2);
                       jLabel14.setText((Double.toString(d.getStock())));
                       Factura fac = new Factura();
                       fac.setCantidad(aux2);
                       fac.precioUnidad(d.getCosto());
                       fac.setSubtotal();
                       fac.setIva();
                       fac.setTotal();
                       jLabel10.setText(Double.toString(fac.getSubtotal()));
                       jLabel11.setText(Double.toString(fac.getIva()));
                       jLabel12.setText(Double.toString(fac.getTotal()));
                       
                       jLabel15.setText(d.getTipo());
                       listaFact.add(fac);
                   }}
            for (Comestibles d : ControlStock.listaCome) {
                    if (d.getNombre().equals(aux)) {
                        d.removeStock(aux2);
                        jLabel14.setText((Double.toString(d.getStock())));
                        Factura fac = new Factura();
                        fac.setCantidad(aux2);
                        fac.precioUnidad(d.getCosto());
                        fac.setSubtotal();
                        fac.setIva();
                        fac.setTotal();
                        jLabel10.setText(Double.toString(fac.getSubtotal()));
                        jLabel11.setText(Double.toString(fac.getIva()));
                        jLabel12.setText(Double.toString(fac.getTotal()));
                        jLabel15.setText(d.getTipo());

                        listaFact.add(fac);
                    }
                }
            for (Utensilios d : ControlStock.listaUten) {
                    if (d.getNombre().equals(aux)) {
                        d.removeStock(aux2);
                        jLabel14.setText((Double.toString(d.getStock())));
                        Factura fac = new Factura();
                        fac.setCantidad(aux2);
                        fac.precioUnidad(d.getCosto());
                        fac.setSubtotal();
                        fac.setIva();
                        fac.setTotal();
                        jLabel10.setText(Double.toString(fac.getSubtotal()));
                        jLabel11.setText(Double.toString(fac.getIva()));
                        jLabel12.setText(Double.toString(fac.getTotal()));
                        jLabel15.setText(d.getTipo());

                        listaFact.add(fac);
                    }
                }
            for (Oficina d : ControlStock.listaOfi) {
                    if (d.getNombre().equals(aux)) {
                        d.removeStock(aux2);
                        jLabel14.setText((Double.toString(d.getStock())));
                        Factura fac = new Factura();
                        fac.setCantidad(aux2);
                        fac.precioUnidad(d.getCosto());
                        fac.setSubtotal();
                        fac.setIva();
                        fac.setTotal();
                        jLabel10.setText(Double.toString(fac.getSubtotal()));
                        jLabel11.setText(Double.toString(fac.getIva()));
                        jLabel12.setText(Double.toString(fac.getTotal()));
                        jLabel15.setText(d.getTipo());

                        listaFact.add(fac);
                    }
                }
            
            
        }catch (Exception e) {
            System.err.println("Error al leer del archivo.");
            System.exit(1);
        } 
            
            


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        double aux;
        double total = 0;
        double subtotal = 0;
        double iva = 0;
        for(Factura d : listaFact){
            aux = d.getTotal();
            total = total + aux;
            subtotal = subtotal + d.getSubtotal() ;
            iva = iva + d.getIva();
        }
        jLabel12.setText(Double.toString(total));
        jLabel10.setText(Double.toString(subtotal));
        jLabel11.setText(Double.toString(iva));
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
